# site settings
title: PS
subtitle: "*Add subtitle*"
email: pss4817@rit.edu
description: "*add description*"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pspegar.github.io" # the base hostname & protocol for your site

author: Patrick Spegar
street_address: 350 Taylor Road
city: Honeoye Falls
state: NY
zip_code: 14472
country: United States of America
phone: (585) 491-2744

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  LinkedIn: "www.linkedin.com/in/patrick-spegar"

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
